### ISSUE TITLE
IResposity返回的是 IList<T>如何实现数据库分页

### ISSUE THREAD

**Issue by yruson** [TripleView/SummerBoot#1]
如题，IResposity接口返回的是 IList<T>。如果要实现数据分页或过滤的话。
那么是先把所有数据读到内存，再来进行分页或过滤。

**Comment by woailibain** [comment]
正常来说Repository的每一个方法返回的都是已经分页后的数据。应该现在还没集成好，否则Repository应该要接收一个Pageable参数用作分页

**Comment by TripleView** [comment]
功能已实现。用法参考example项目
