### ISSUE TITLE
事务的嵌套

### ISSUE THREAD

**Issue by smallDragonOne** [TripleView/SummerBoot#2]
我觉得事务嵌套  用一个bool属性来控制是否新建一个事务，否则应该默认同一个事务，现在的做法有点看不懂，直接就数量减一，默认是不处理嵌套的事务提交了吗？

**Comment by TripleView** [comment]
> 我觉得事务嵌套 用一个bool属性来控制是否新建一个事务，否则应该默认同一个事务，现在的做法有点看不懂，直接就数量减一，默认是不处理嵌套的事务提交了吗？
现在的做法是如果上级方法启用了事务，那么下级方法就共用这个事务
