### ISSUE TITLE
能否提供项目的整体配置文件说明

### ISSUE THREAD

**Issue by yetao-study** [TripleView/SummerBoot#5]
能否提供类似于SpringBoot项目的整体配置文件说明appsettings.json
如：访问地址的配置，http服务端口号的配置等
现在做测试只能用http://localhost:5000的地址访问
这是一个很好的项目，我是从SpringBoot过来的，不太想了解C#中关于请求协议，解析等细节，只想将这个框架用于业务的实现上，这应该也是Boot项目的主要目标。

**Comment by TripleView** [comment]
你好，项目已经重构，并且提供提供了完整的说明文档。
